//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChGlyphs : ChVisualShape {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ChGlyphs(global::System.IntPtr cPtr, bool cMemoryOwn) : base(corePINVOKE.ChGlyphs_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChGlyphs obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          corePINVOKE.delete_ChGlyphs(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ChGlyphs() : this(corePINVOKE.new_ChGlyphs(), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public ChGlyphs.eCh_GlyphType GetDrawMode() {
    ChGlyphs.eCh_GlyphType ret = (ChGlyphs.eCh_GlyphType)corePINVOKE.ChGlyphs_GetDrawMode(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetDrawMode(ChGlyphs.eCh_GlyphType mmode) {
    corePINVOKE.ChGlyphs_SetDrawMode(swigCPtr, (int)mmode);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reserve(uint n_glyphs) {
    corePINVOKE.ChGlyphs_Reserve(swigCPtr, n_glyphs);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetNumberOfGlyphs() {
    uint ret = corePINVOKE.ChGlyphs_GetNumberOfGlyphs(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetGlyphsSize() {
    double ret = corePINVOKE.ChGlyphs_GetGlyphsSize(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetGlyphsSize(double msize) {
    corePINVOKE.ChGlyphs_SetGlyphsSize(swigCPtr, msize);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetZbufferHide(bool mhide) {
    corePINVOKE.ChGlyphs_SetZbufferHide(swigCPtr, mhide);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetZbufferHide() {
    bool ret = corePINVOKE.ChGlyphs_GetZbufferHide(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetGlyphPoint(uint id, ChVectorD mpoint, ChColor mcolor) {
    corePINVOKE.ChGlyphs_SetGlyphPoint__SWIG_0(swigCPtr, id, ChVectorD.getCPtr(mpoint), ChColor.getCPtr(mcolor));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlyphPoint(uint id, ChVectorD mpoint) {
    corePINVOKE.ChGlyphs_SetGlyphPoint__SWIG_1(swigCPtr, id, ChVectorD.getCPtr(mpoint));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlyphVector(uint id, ChVectorD mpoint, ChVectorD mvector, ChColor mcolor) {
    corePINVOKE.ChGlyphs_SetGlyphVector__SWIG_0(swigCPtr, id, ChVectorD.getCPtr(mpoint), ChVectorD.getCPtr(mvector), ChColor.getCPtr(mcolor));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlyphVector(uint id, ChVectorD mpoint, ChVectorD mvector) {
    corePINVOKE.ChGlyphs_SetGlyphVector__SWIG_1(swigCPtr, id, ChVectorD.getCPtr(mpoint), ChVectorD.getCPtr(mvector));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlyphVectorLocal(uint id, ChVectorD mpoint, ChVectorD mvector, ChQuaternionD mrot, ChColor mcolor) {
    corePINVOKE.ChGlyphs_SetGlyphVectorLocal__SWIG_0(swigCPtr, id, ChVectorD.getCPtr(mpoint), ChVectorD.getCPtr(mvector), ChQuaternionD.getCPtr(mrot), ChColor.getCPtr(mcolor));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlyphVectorLocal(uint id, ChVectorD mpoint, ChVectorD mvector, ChQuaternionD mrot) {
    corePINVOKE.ChGlyphs_SetGlyphVectorLocal__SWIG_1(swigCPtr, id, ChVectorD.getCPtr(mpoint), ChVectorD.getCPtr(mvector), ChQuaternionD.getCPtr(mrot));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlyphCoordsys(uint id, ChCoordsysD mcoord) {
    corePINVOKE.ChGlyphs_SetGlyphCoordsys(swigCPtr, id, ChCoordsysD.getCPtr(mcoord));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetGlyphTensor(uint id, ChVectorD mpoint, ChQuaternionD mbasis, ChVectorD eigenvalues) {
    corePINVOKE.ChGlyphs_SetGlyphTensor(swigCPtr, id, ChVectorD.getCPtr(mpoint), ChQuaternionD.getCPtr(mbasis), ChVectorD.getCPtr(eigenvalues));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__vectorT_chrono__geometry__ChProperty_p_t getProperties() {
    SWIGTYPE_p_std__vectorT_chrono__geometry__ChProperty_p_t ret = new SWIGTYPE_p_std__vectorT_chrono__geometry__ChProperty_p_t(corePINVOKE.ChGlyphs_getProperties(swigCPtr), true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void AddProperty(SWIGTYPE_p_chrono__geometry__ChProperty mprop) {
    corePINVOKE.ChGlyphs_AddProperty(swigCPtr, SWIGTYPE_p_chrono__geometry__ChProperty.getCPtr(mprop));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void ArchiveOut(SWIGTYPE_p_chrono__ChArchiveOut marchive) {
    corePINVOKE.ChGlyphs_ArchiveOut(swigCPtr, SWIGTYPE_p_chrono__ChArchiveOut.getCPtr(marchive));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void ArchiveIn(SWIGTYPE_p_chrono__ChArchiveIn marchive) {
    corePINVOKE.ChGlyphs_ArchiveIn(swigCPtr, SWIGTYPE_p_chrono__ChArchiveIn.getCPtr(marchive));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_ChVectorD points {
    set {
      corePINVOKE.ChGlyphs_points_set(swigCPtr, vector_ChVectorD.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_points_get(swigCPtr);
      vector_ChVectorD ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_ChVectorD(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChGlyphs.eCh_GlyphLength glyph_length_type {
    set {
      corePINVOKE.ChGlyphs_glyph_length_type_set(swigCPtr, (int)value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ChGlyphs.eCh_GlyphLength ret = (ChGlyphs.eCh_GlyphLength)corePINVOKE.ChGlyphs_glyph_length_type_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string glyph_length_prop {
    set {
      corePINVOKE.ChGlyphs_glyph_length_prop_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = corePINVOKE.ChGlyphs_glyph_length_prop_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double glyph_scalelenght {
    set {
      corePINVOKE.ChGlyphs_glyph_scalelenght_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = corePINVOKE.ChGlyphs_glyph_scalelenght_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChGlyphs.eCh_GlyphWidth glyph_width_type {
    set {
      corePINVOKE.ChGlyphs_glyph_width_type_set(swigCPtr, (int)value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ChGlyphs.eCh_GlyphWidth ret = (ChGlyphs.eCh_GlyphWidth)corePINVOKE.ChGlyphs_glyph_width_type_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string glyph_width_prop {
    set {
      corePINVOKE.ChGlyphs_glyph_width_prop_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = corePINVOKE.ChGlyphs_glyph_width_prop_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double glyph_scalewidth {
    set {
      corePINVOKE.ChGlyphs_glyph_scalewidth_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = corePINVOKE.ChGlyphs_glyph_scalewidth_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChGlyphs.eCh_GlyphBasis glyph_basis_type {
    set {
      corePINVOKE.ChGlyphs_glyph_basis_type_set(swigCPtr, (int)value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ChGlyphs.eCh_GlyphBasis ret = (ChGlyphs.eCh_GlyphBasis)corePINVOKE.ChGlyphs_glyph_basis_type_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string glyph_basis_prop {
    set {
      corePINVOKE.ChGlyphs_glyph_basis_prop_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = corePINVOKE.ChGlyphs_glyph_basis_prop_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChQuaternionD glyph_basis_constant {
    set {
      corePINVOKE.ChGlyphs_glyph_basis_constant_set(swigCPtr, ChQuaternionD.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_glyph_basis_constant_get(swigCPtr);
      ChQuaternionD ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChQuaternionD(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChGlyphs.eCh_GlyphEigenvalues glyph_eigenvalues_type {
    set {
      corePINVOKE.ChGlyphs_glyph_eigenvalues_type_set(swigCPtr, (int)value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ChGlyphs.eCh_GlyphEigenvalues ret = (ChGlyphs.eCh_GlyphEigenvalues)corePINVOKE.ChGlyphs_glyph_eigenvalues_type_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string glyph_eigenvalues_prop {
    set {
      corePINVOKE.ChGlyphs_glyph_eigenvalues_prop_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = corePINVOKE.ChGlyphs_glyph_eigenvalues_prop_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChVectorD glyph_eigenvalue_constant {
    set {
      corePINVOKE.ChGlyphs_glyph_eigenvalue_constant_set(swigCPtr, ChVectorD.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_glyph_eigenvalue_constant_get(swigCPtr);
      ChVectorD ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChVectorD(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChGlyphs.eCh_GlyphColor glyph_color_type {
    set {
      corePINVOKE.ChGlyphs_glyph_color_type_set(swigCPtr, (int)value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      ChGlyphs.eCh_GlyphColor ret = (ChGlyphs.eCh_GlyphColor)corePINVOKE.ChGlyphs_glyph_color_type_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string glyph_color_prop {
    set {
      corePINVOKE.ChGlyphs_glyph_color_prop_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = corePINVOKE.ChGlyphs_glyph_color_prop_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ChColor glyph_color_constant {
    set {
      corePINVOKE.ChGlyphs_glyph_color_constant_set(swigCPtr, ChColor.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_glyph_color_constant_get(swigCPtr);
      ChColor ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChColor(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double glyph_colormap_startscale {
    set {
      corePINVOKE.ChGlyphs_glyph_colormap_startscale_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = corePINVOKE.ChGlyphs_glyph_colormap_startscale_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double glyph_colormap_endscale {
    set {
      corePINVOKE.ChGlyphs_glyph_colormap_endscale_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = corePINVOKE.ChGlyphs_glyph_colormap_endscale_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool vector_tip {
    set {
      corePINVOKE.ChGlyphs_vector_tip_set(swigCPtr, value);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = corePINVOKE.ChGlyphs_vector_tip_get(swigCPtr);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_chrono__geometry__ChProperty_p_t m_properties {
    set {
      corePINVOKE.ChGlyphs_m_properties_set(swigCPtr, SWIGTYPE_p_std__vectorT_chrono__geometry__ChProperty_p_t.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_m_properties_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_chrono__geometry__ChProperty_p_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_chrono__geometry__ChProperty_p_t(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_chrono__ChColor_t colors {
    set {
      corePINVOKE.ChGlyphs_colors_set(swigCPtr, SWIGTYPE_p_std__vectorT_chrono__ChColor_t.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_colors_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_chrono__ChColor_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_chrono__ChColor_t(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public vector_ChVectorD vectors {
    set {
      corePINVOKE.ChGlyphs_vectors_set(swigCPtr, vector_ChVectorD.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_vectors_get(swigCPtr);
      vector_ChVectorD ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_ChVectorD(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_chrono__ChQuaternionT_double_t_t rotations {
    set {
      corePINVOKE.ChGlyphs_rotations_set(swigCPtr, SWIGTYPE_p_std__vectorT_chrono__ChQuaternionT_double_t_t.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_rotations_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_chrono__ChQuaternionT_double_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_chrono__ChQuaternionT_double_t_t(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public vector_ChVectorD eigenvalues {
    set {
      corePINVOKE.ChGlyphs_eigenvalues_set(swigCPtr, vector_ChVectorD.getCPtr(value));
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = corePINVOKE.ChGlyphs_eigenvalues_get(swigCPtr);
      vector_ChVectorD ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_ChVectorD(cPtr, false);
      if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public enum eCh_GlyphType {
    GLYPH_POINT = 0,
    GLYPH_VECTOR,
    GLYPH_COORDSYS,
    GLYPH_TENSOR
  }

  public enum eCh_GlyphLength {
    CONSTANT = 0,
    PROPERTY
  }

  public enum eCh_GlyphWidth {
    CONSTANT = 0,
    PROPERTY
  }

  public enum eCh_GlyphBasis {
    CONSTANT = 0,
    PROPERTY
  }

  public enum eCh_GlyphEigenvalues {
    CONSTANT = 0,
    PROPERTY
  }

  public enum eCh_GlyphColor {
    CONSTANT = 0,
    PROPERTY
  }

}
