/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_vehicle_WRAP_H_
#define SWIG_vehicle_WRAP_H_

class SwigDirector_ChExternalDriver_DataGeneratorFunctor : public chrono::vehicle::ChExternalDriver::DataGeneratorFunctor, public Swig::Director {

public:
    SwigDirector_ChExternalDriver_DataGeneratorFunctor(std::string const &type,std::string const &id);
    virtual ~SwigDirector_ChExternalDriver_DataGeneratorFunctor();
    virtual void Serialize(chrono::vehicle::ChJSONWriter &writer);
    virtual bool HasData();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackSerialize, SWIG_Callback1_t callbackHasData);

private:
    SWIG_Callback0_t swig_callbackSerialize;
    SWIG_Callback1_t swig_callbackHasData;
    void swig_init_callbacks();
};

class SwigDirector_ChExternalDriver_DataParserFunctor : public chrono::vehicle::ChExternalDriver::DataParserFunctor, public Swig::Director {

public:
    SwigDirector_ChExternalDriver_DataParserFunctor(std::string const &type);
    virtual ~SwigDirector_ChExternalDriver_DataParserFunctor();
    virtual void Deserialize(chrono::vehicle::ChJSONReader &reader);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackDeserialize);

private:
    SWIG_Callback0_t swig_callbackDeserialize;
    void swig_init_callbacks();
};

class SwigDirector_SoilParametersCallback : public chrono::vehicle::SCMTerrain::SoilParametersCallback, public Swig::Director {

public:
    SwigDirector_SoilParametersCallback();
    virtual ~SwigDirector_SoilParametersCallback();
    virtual void Set(chrono::ChVector< > const &loc,double &Bekker_Kphi,double &Bekker_Kc,double &Bekker_n,double &Mohr_cohesion,double &Mohr_friction,double &Janosi_shear,double &elastic_K,double &damping_R);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *, void *, void *, void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackSet);

private:
    SWIG_Callback0_t swig_callbackSet;
    void swig_init_callbacks();
};


#endif
