/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_core_WRAP_H_
#define SWIG_core_WRAP_H_

class SwigDirector_BroadphaseCallback : public chrono::collision::ChCollisionSystem::BroadphaseCallback, public Swig::Director {

public:
    SwigDirector_BroadphaseCallback();
    virtual ~SwigDirector_BroadphaseCallback();
    virtual bool OnBroadphase(chrono::collision::ChCollisionModel *modelA, chrono::collision::ChCollisionModel *modelB);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnBroadphase);

private:
    SWIG_Callback0_t swig_callbackOnBroadphase;
    void swig_init_callbacks();
};

class SwigDirector_NarrowphaseCallback : public chrono::collision::ChCollisionSystem::NarrowphaseCallback, public Swig::Director {

public:
    SwigDirector_NarrowphaseCallback();
    virtual ~SwigDirector_NarrowphaseCallback();
    virtual bool OnNarrowphase(ChCollisionInfo &contactinfo);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnNarrowphase);

private:
    SWIG_Callback0_t swig_callbackOnNarrowphase;
    void swig_init_callbacks();
};

class SwigDirector_VisualizationCallback : public chrono::collision::ChCollisionSystem::VisualizationCallback, public Swig::Director {

public:
    SwigDirector_VisualizationCallback();
    virtual ~SwigDirector_VisualizationCallback();
    virtual void DrawLine(chrono::ChVector< > const &from, chrono::ChVector< > const &to, ChColor const &color);
    virtual double GetNormalScale() const;

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackDrawLine, SWIG_Callback1_t callbackGetNormalScale);

private:
    SWIG_Callback0_t swig_callbackDrawLine;
    SWIG_Callback1_t swig_callbackGetNormalScale;
    void swig_init_callbacks();
};

class SwigDirector_ChFunction : public chrono::ChFunction, public Swig::Director {

public:
    SwigDirector_ChFunction();
    SwigDirector_ChFunction(chrono::ChFunction const &other);
    virtual ~SwigDirector_ChFunction();
    virtual chrono::ChFunction *Clone() const;
    virtual chrono::ChFunction::FunctionType Get_Type() const;
    virtual double Get_y(double x) const;
    virtual double Get_y_dx(double x) const;
    virtual double Get_y_dxdx(double x) const;
    virtual double Get_weight(double x) const;
    virtual void Estimate_x_range(double &xmin, double &xmax) const;
    virtual void Estimate_y_range(double xmin, double xmax, double &ymin, double &ymax, int derivate) const;
    virtual double Get_y_dN(double x, int derivate) const;
    virtual void Update(double const x);
    virtual double Compute_max(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_min(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_mean(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_sqrmean(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_int(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Get_Ca_pos() const;
    virtual double Get_Ca_neg() const;
    virtual double Get_Cv() const;
    virtual int HandleNumber() const;
    virtual bool HandleAccess(int handle_id, double mx, double my, bool set_mode);
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual int FilePostscriptPlot(ChFile_ps *m_file, int plotY, int plotDY, int plotDDY);
    virtual int FileAsciiPairsSave(chrono::ChStreamOutAscii &m_file, double xmin = 0, double xmax = 1, int msamples = 200);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(double, double, void *, void *, int);
    typedef double (SWIGSTDCALL* SWIG_Callback7_t)(double, int);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback9_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback10_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback13_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback15_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback16_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback17_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback18_t)(int, double, double, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback21_t)(void *, int, int, int);
    typedef int (SWIGSTDCALL* SWIG_Callback22_t)(void *, double, double, int);
    typedef int (SWIGSTDCALL* SWIG_Callback23_t)(void *, double, double);
    typedef int (SWIGSTDCALL* SWIG_Callback24_t)(void *, double);
    typedef int (SWIGSTDCALL* SWIG_Callback25_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackGet_Type, SWIG_Callback1_t callbackGet_y, SWIG_Callback2_t callbackGet_y_dx, SWIG_Callback3_t callbackGet_y_dxdx, SWIG_Callback4_t callbackGet_weight, SWIG_Callback5_t callbackEstimate_x_range, SWIG_Callback6_t callbackEstimate_y_range, SWIG_Callback7_t callbackGet_y_dN, SWIG_Callback8_t callbackUpdate, SWIG_Callback9_t callbackCompute_max, SWIG_Callback10_t callbackCompute_min, SWIG_Callback11_t callbackCompute_mean, SWIG_Callback12_t callbackCompute_sqrmean, SWIG_Callback13_t callbackCompute_int, SWIG_Callback14_t callbackGet_Ca_pos, SWIG_Callback15_t callbackGet_Ca_neg, SWIG_Callback16_t callbackGet_Cv, SWIG_Callback17_t callbackHandleNumber, SWIG_Callback18_t callbackHandleAccess, SWIG_Callback19_t callbackArchiveOut, SWIG_Callback20_t callbackArchiveIn, SWIG_Callback21_t callbackFilePostscriptPlot, SWIG_Callback22_t callbackFileAsciiPairsSave__SWIG_0, SWIG_Callback23_t callbackFileAsciiPairsSave__SWIG_1, SWIG_Callback24_t callbackFileAsciiPairsSave__SWIG_2, SWIG_Callback25_t callbackFileAsciiPairsSave__SWIG_3);

private:
    SWIG_Callback0_t swig_callbackGet_Type;
    SWIG_Callback1_t swig_callbackGet_y;
    SWIG_Callback2_t swig_callbackGet_y_dx;
    SWIG_Callback3_t swig_callbackGet_y_dxdx;
    SWIG_Callback4_t swig_callbackGet_weight;
    SWIG_Callback5_t swig_callbackEstimate_x_range;
    SWIG_Callback6_t swig_callbackEstimate_y_range;
    SWIG_Callback7_t swig_callbackGet_y_dN;
    SWIG_Callback8_t swig_callbackUpdate;
    SWIG_Callback9_t swig_callbackCompute_max;
    SWIG_Callback10_t swig_callbackCompute_min;
    SWIG_Callback11_t swig_callbackCompute_mean;
    SWIG_Callback12_t swig_callbackCompute_sqrmean;
    SWIG_Callback13_t swig_callbackCompute_int;
    SWIG_Callback14_t swig_callbackGet_Ca_pos;
    SWIG_Callback15_t swig_callbackGet_Ca_neg;
    SWIG_Callback16_t swig_callbackGet_Cv;
    SWIG_Callback17_t swig_callbackHandleNumber;
    SWIG_Callback18_t swig_callbackHandleAccess;
    SWIG_Callback19_t swig_callbackArchiveOut;
    SWIG_Callback20_t swig_callbackArchiveIn;
    SWIG_Callback21_t swig_callbackFilePostscriptPlot;
    SWIG_Callback22_t swig_callbackFileAsciiPairsSave__SWIG_0;
    SWIG_Callback23_t swig_callbackFileAsciiPairsSave__SWIG_1;
    SWIG_Callback24_t swig_callbackFileAsciiPairsSave__SWIG_2;
    SWIG_Callback25_t swig_callbackFileAsciiPairsSave__SWIG_3;
    void swig_init_callbacks();
};

class SwigDirector_ChFunction_Setpoint : public chrono::ChFunction_Setpoint, public Swig::Director {

public:
    SwigDirector_ChFunction_Setpoint();
    SwigDirector_ChFunction_Setpoint(chrono::ChFunction_Setpoint const &other);
    virtual ~SwigDirector_ChFunction_Setpoint();
    virtual chrono::ChFunction_Setpoint *Clone() const;
    virtual chrono::ChFunction::FunctionType Get_Type() const;
    virtual double Get_y(double x) const;
    virtual double Get_y_dx(double x) const;
    virtual double Get_y_dxdx(double x) const;
    virtual double Get_weight(double x) const;
    virtual void Estimate_x_range(double &xmin, double &xmax) const;
    virtual void Estimate_y_range(double xmin, double xmax, double &ymin, double &ymax, int derivate) const;
    virtual double Get_y_dN(double x, int derivate) const;
    virtual void Update(double const x);
    virtual double Compute_max(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_min(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_mean(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_sqrmean(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_int(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Get_Ca_pos() const;
    virtual double Get_Ca_neg() const;
    virtual double Get_Cv() const;
    virtual int HandleNumber() const;
    virtual bool HandleAccess(int handle_id, double mx, double my, bool set_mode);
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual int FilePostscriptPlot(ChFile_ps *m_file, int plotY, int plotDY, int plotDDY);
    virtual int FileAsciiPairsSave(chrono::ChStreamOutAscii &m_file, double xmin = 0, double xmax = 1, int msamples = 200);
    virtual void SetSetpoint(double setpoint, double x);
    virtual void SetSetpointAndDerivatives(double setpoint, double setpoint_dx, double setpoint_dxdx);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(double, double, void *, void *, int);
    typedef double (SWIGSTDCALL* SWIG_Callback7_t)(double, int);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback9_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback10_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback13_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback15_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback16_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback17_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback18_t)(int, double, double, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback21_t)(void *, int, int, int);
    typedef int (SWIGSTDCALL* SWIG_Callback22_t)(void *, double, double, int);
    typedef int (SWIGSTDCALL* SWIG_Callback23_t)(void *, double, double);
    typedef int (SWIGSTDCALL* SWIG_Callback24_t)(void *, double);
    typedef int (SWIGSTDCALL* SWIG_Callback25_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback26_t)(double, double);
    typedef void (SWIGSTDCALL* SWIG_Callback27_t)(double, double, double);
    void swig_connect_director(SWIG_Callback0_t callbackGet_Type, SWIG_Callback1_t callbackGet_y, SWIG_Callback2_t callbackGet_y_dx, SWIG_Callback3_t callbackGet_y_dxdx, SWIG_Callback4_t callbackGet_weight, SWIG_Callback5_t callbackEstimate_x_range, SWIG_Callback6_t callbackEstimate_y_range, SWIG_Callback7_t callbackGet_y_dN, SWIG_Callback8_t callbackUpdate, SWIG_Callback9_t callbackCompute_max, SWIG_Callback10_t callbackCompute_min, SWIG_Callback11_t callbackCompute_mean, SWIG_Callback12_t callbackCompute_sqrmean, SWIG_Callback13_t callbackCompute_int, SWIG_Callback14_t callbackGet_Ca_pos, SWIG_Callback15_t callbackGet_Ca_neg, SWIG_Callback16_t callbackGet_Cv, SWIG_Callback17_t callbackHandleNumber, SWIG_Callback18_t callbackHandleAccess, SWIG_Callback19_t callbackArchiveOut, SWIG_Callback20_t callbackArchiveIn, SWIG_Callback21_t callbackFilePostscriptPlot, SWIG_Callback22_t callbackFileAsciiPairsSave__SWIG_0, SWIG_Callback23_t callbackFileAsciiPairsSave__SWIG_1, SWIG_Callback24_t callbackFileAsciiPairsSave__SWIG_2, SWIG_Callback25_t callbackFileAsciiPairsSave__SWIG_3, SWIG_Callback26_t callbackSetSetpoint, SWIG_Callback27_t callbackSetSetpointAndDerivatives);

private:
    SWIG_Callback0_t swig_callbackGet_Type;
    SWIG_Callback1_t swig_callbackGet_y;
    SWIG_Callback2_t swig_callbackGet_y_dx;
    SWIG_Callback3_t swig_callbackGet_y_dxdx;
    SWIG_Callback4_t swig_callbackGet_weight;
    SWIG_Callback5_t swig_callbackEstimate_x_range;
    SWIG_Callback6_t swig_callbackEstimate_y_range;
    SWIG_Callback7_t swig_callbackGet_y_dN;
    SWIG_Callback8_t swig_callbackUpdate;
    SWIG_Callback9_t swig_callbackCompute_max;
    SWIG_Callback10_t swig_callbackCompute_min;
    SWIG_Callback11_t swig_callbackCompute_mean;
    SWIG_Callback12_t swig_callbackCompute_sqrmean;
    SWIG_Callback13_t swig_callbackCompute_int;
    SWIG_Callback14_t swig_callbackGet_Ca_pos;
    SWIG_Callback15_t swig_callbackGet_Ca_neg;
    SWIG_Callback16_t swig_callbackGet_Cv;
    SWIG_Callback17_t swig_callbackHandleNumber;
    SWIG_Callback18_t swig_callbackHandleAccess;
    SWIG_Callback19_t swig_callbackArchiveOut;
    SWIG_Callback20_t swig_callbackArchiveIn;
    SWIG_Callback21_t swig_callbackFilePostscriptPlot;
    SWIG_Callback22_t swig_callbackFileAsciiPairsSave__SWIG_0;
    SWIG_Callback23_t swig_callbackFileAsciiPairsSave__SWIG_1;
    SWIG_Callback24_t swig_callbackFileAsciiPairsSave__SWIG_2;
    SWIG_Callback25_t swig_callbackFileAsciiPairsSave__SWIG_3;
    SWIG_Callback26_t swig_callbackSetSetpoint;
    SWIG_Callback27_t swig_callbackSetSetpointAndDerivatives;
    void swig_init_callbacks();
};

class SwigDirector_ChFunction_SetpointCallback : public chrono::ChFunction_SetpointCallback, public Swig::Director {

public:
    SwigDirector_ChFunction_SetpointCallback();
    SwigDirector_ChFunction_SetpointCallback(chrono::ChFunction_SetpointCallback const &other);
    virtual ~SwigDirector_ChFunction_SetpointCallback();
    virtual chrono::ChFunction_Setpoint *Clone() const;
    virtual chrono::ChFunction::FunctionType Get_Type() const;
    virtual double Get_y(double x) const;
    virtual double Get_y_dx(double x) const;
    virtual double Get_y_dxdx(double x) const;
    virtual double Get_weight(double x) const;
    virtual void Estimate_x_range(double &xmin, double &xmax) const;
    virtual void Estimate_y_range(double xmin, double xmax, double &ymin, double &ymax, int derivate) const;
    virtual double Get_y_dN(double x, int derivate) const;
    virtual void Update(double const x);
    virtual double Compute_max(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_min(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_mean(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_sqrmean(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Compute_int(double xmin, double xmax, double sampling_step, int derivate) const;
    virtual double Get_Ca_pos() const;
    virtual double Get_Ca_neg() const;
    virtual double Get_Cv() const;
    virtual int HandleNumber() const;
    virtual bool HandleAccess(int handle_id, double mx, double my, bool set_mode);
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual int FilePostscriptPlot(ChFile_ps *m_file, int plotY, int plotDY, int plotDDY);
    virtual int FileAsciiPairsSave(chrono::ChStreamOutAscii &m_file, double xmin = 0, double xmax = 1, int msamples = 200);
    virtual void SetSetpoint(double setpoint, double x);
    virtual void SetSetpointAndDerivatives(double setpoint, double setpoint_dx, double setpoint_dxdx);
    virtual double SetpointCallback(double const x);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback3_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(double, double, void *, void *, int);
    typedef double (SWIGSTDCALL* SWIG_Callback7_t)(double, int);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(double);
    typedef double (SWIGSTDCALL* SWIG_Callback9_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback10_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback13_t)(double, double, double, int);
    typedef double (SWIGSTDCALL* SWIG_Callback14_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback15_t)();
    typedef double (SWIGSTDCALL* SWIG_Callback16_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback17_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback18_t)(int, double, double, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback21_t)(void *, int, int, int);
    typedef int (SWIGSTDCALL* SWIG_Callback22_t)(void *, double, double, int);
    typedef int (SWIGSTDCALL* SWIG_Callback23_t)(void *, double, double);
    typedef int (SWIGSTDCALL* SWIG_Callback24_t)(void *, double);
    typedef int (SWIGSTDCALL* SWIG_Callback25_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback26_t)(double, double);
    typedef void (SWIGSTDCALL* SWIG_Callback27_t)(double, double, double);
    typedef double (SWIGSTDCALL* SWIG_Callback28_t)(double);
    void swig_connect_director(SWIG_Callback0_t callbackGet_Type, SWIG_Callback1_t callbackGet_y, SWIG_Callback2_t callbackGet_y_dx, SWIG_Callback3_t callbackGet_y_dxdx, SWIG_Callback4_t callbackGet_weight, SWIG_Callback5_t callbackEstimate_x_range, SWIG_Callback6_t callbackEstimate_y_range, SWIG_Callback7_t callbackGet_y_dN, SWIG_Callback8_t callbackUpdate, SWIG_Callback9_t callbackCompute_max, SWIG_Callback10_t callbackCompute_min, SWIG_Callback11_t callbackCompute_mean, SWIG_Callback12_t callbackCompute_sqrmean, SWIG_Callback13_t callbackCompute_int, SWIG_Callback14_t callbackGet_Ca_pos, SWIG_Callback15_t callbackGet_Ca_neg, SWIG_Callback16_t callbackGet_Cv, SWIG_Callback17_t callbackHandleNumber, SWIG_Callback18_t callbackHandleAccess, SWIG_Callback19_t callbackArchiveOut, SWIG_Callback20_t callbackArchiveIn, SWIG_Callback21_t callbackFilePostscriptPlot, SWIG_Callback22_t callbackFileAsciiPairsSave__SWIG_0, SWIG_Callback23_t callbackFileAsciiPairsSave__SWIG_1, SWIG_Callback24_t callbackFileAsciiPairsSave__SWIG_2, SWIG_Callback25_t callbackFileAsciiPairsSave__SWIG_3, SWIG_Callback26_t callbackSetSetpoint, SWIG_Callback27_t callbackSetSetpointAndDerivatives, SWIG_Callback28_t callbackSetpointCallback);

private:
    SWIG_Callback0_t swig_callbackGet_Type;
    SWIG_Callback1_t swig_callbackGet_y;
    SWIG_Callback2_t swig_callbackGet_y_dx;
    SWIG_Callback3_t swig_callbackGet_y_dxdx;
    SWIG_Callback4_t swig_callbackGet_weight;
    SWIG_Callback5_t swig_callbackEstimate_x_range;
    SWIG_Callback6_t swig_callbackEstimate_y_range;
    SWIG_Callback7_t swig_callbackGet_y_dN;
    SWIG_Callback8_t swig_callbackUpdate;
    SWIG_Callback9_t swig_callbackCompute_max;
    SWIG_Callback10_t swig_callbackCompute_min;
    SWIG_Callback11_t swig_callbackCompute_mean;
    SWIG_Callback12_t swig_callbackCompute_sqrmean;
    SWIG_Callback13_t swig_callbackCompute_int;
    SWIG_Callback14_t swig_callbackGet_Ca_pos;
    SWIG_Callback15_t swig_callbackGet_Ca_neg;
    SWIG_Callback16_t swig_callbackGet_Cv;
    SWIG_Callback17_t swig_callbackHandleNumber;
    SWIG_Callback18_t swig_callbackHandleAccess;
    SWIG_Callback19_t swig_callbackArchiveOut;
    SWIG_Callback20_t swig_callbackArchiveIn;
    SWIG_Callback21_t swig_callbackFilePostscriptPlot;
    SWIG_Callback22_t swig_callbackFileAsciiPairsSave__SWIG_0;
    SWIG_Callback23_t swig_callbackFileAsciiPairsSave__SWIG_1;
    SWIG_Callback24_t swig_callbackFileAsciiPairsSave__SWIG_2;
    SWIG_Callback25_t swig_callbackFileAsciiPairsSave__SWIG_3;
    SWIG_Callback26_t swig_callbackSetSetpoint;
    SWIG_Callback27_t swig_callbackSetSetpointAndDerivatives;
    SWIG_Callback28_t swig_callbackSetpointCallback;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionRotation : public chrono::ChFunctionRotation, public Swig::Director {

public:
    SwigDirector_ChFunctionRotation();
    SwigDirector_ChFunctionRotation(chrono::ChFunctionRotation const &other);
    virtual ~SwigDirector_ChFunctionRotation();
    virtual chrono::ChFunctionRotation *Clone() const;
    virtual chrono::ChQuaternion< > Get_q(double s) const;
    virtual chrono::ChVector< > Get_w_loc(double s) const;
    virtual chrono::ChVector< > Get_a_loc(double s) const;
    virtual void Estimate_s_domain(double &smin, double &smax) const;
    virtual void Update(double const t);
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackGet_q, SWIG_Callback1_t callbackGet_w_loc, SWIG_Callback2_t callbackGet_a_loc, SWIG_Callback3_t callbackEstimate_s_domain, SWIG_Callback4_t callbackUpdate, SWIG_Callback5_t callbackArchiveOut, SWIG_Callback6_t callbackArchiveIn);

private:
    SWIG_Callback0_t swig_callbackGet_q;
    SWIG_Callback1_t swig_callbackGet_w_loc;
    SWIG_Callback2_t swig_callbackGet_a_loc;
    SWIG_Callback3_t swig_callbackEstimate_s_domain;
    SWIG_Callback4_t swig_callbackUpdate;
    SWIG_Callback5_t swig_callbackArchiveOut;
    SWIG_Callback6_t swig_callbackArchiveIn;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionRotation_setpoint : public chrono::ChFunctionRotation_setpoint, public Swig::Director {

public:
    SwigDirector_ChFunctionRotation_setpoint();
    SwigDirector_ChFunctionRotation_setpoint(chrono::ChFunctionRotation_setpoint const &other);
    virtual ~SwigDirector_ChFunctionRotation_setpoint();
    virtual chrono::ChFunctionRotation_setpoint *Clone() const;
    virtual chrono::ChQuaternion< > Get_q(double s) const;
    virtual chrono::ChVector< > Get_w_loc(double s) const;
    virtual chrono::ChVector< > Get_a_loc(double s) const;
    virtual void Estimate_s_domain(double &smin, double &smax) const;
    virtual void Update(double const t);
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual void SetSetpoint(chrono::ChQuaternion< > q_setpoint, double s);
    virtual void SetSetpointAndDerivatives(chrono::ChQuaternion< > q_setpoint, chrono::ChVector< > w_loc_setpoint, chrono::ChVector< > a_loc_setpoint);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackGet_q, SWIG_Callback1_t callbackGet_w_loc, SWIG_Callback2_t callbackGet_a_loc, SWIG_Callback3_t callbackEstimate_s_domain, SWIG_Callback4_t callbackUpdate, SWIG_Callback5_t callbackArchiveOut, SWIG_Callback6_t callbackArchiveIn, SWIG_Callback7_t callbackSetSetpoint, SWIG_Callback8_t callbackSetSetpointAndDerivatives);

private:
    SWIG_Callback0_t swig_callbackGet_q;
    SWIG_Callback1_t swig_callbackGet_w_loc;
    SWIG_Callback2_t swig_callbackGet_a_loc;
    SWIG_Callback3_t swig_callbackEstimate_s_domain;
    SWIG_Callback4_t swig_callbackUpdate;
    SWIG_Callback5_t swig_callbackArchiveOut;
    SWIG_Callback6_t swig_callbackArchiveIn;
    SWIG_Callback7_t swig_callbackSetSetpoint;
    SWIG_Callback8_t swig_callbackSetSetpointAndDerivatives;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionPosition : public chrono::ChFunctionPosition, public Swig::Director {

public:
    SwigDirector_ChFunctionPosition();
    SwigDirector_ChFunctionPosition(chrono::ChFunctionPosition const &other);
    virtual ~SwigDirector_ChFunctionPosition();
    virtual chrono::ChFunctionPosition *Clone() const;
    virtual chrono::ChVector< > Get_p(double s) const;
    virtual chrono::ChVector< > Get_p_ds(double s) const;
    virtual chrono::ChVector< > Get_p_dsds(double s) const;
    virtual void Estimate_s_domain(double &smin, double &smax) const;
    virtual void Estimate_boundingbox(chrono::ChVector< > &pmin, chrono::ChVector< > &pmax) const;
    virtual void Update(double const t);
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackGet_p, SWIG_Callback1_t callbackGet_p_ds, SWIG_Callback2_t callbackGet_p_dsds, SWIG_Callback3_t callbackEstimate_s_domain, SWIG_Callback4_t callbackEstimate_boundingbox, SWIG_Callback5_t callbackUpdate, SWIG_Callback6_t callbackArchiveOut, SWIG_Callback7_t callbackArchiveIn);

private:
    SWIG_Callback0_t swig_callbackGet_p;
    SWIG_Callback1_t swig_callbackGet_p_ds;
    SWIG_Callback2_t swig_callbackGet_p_dsds;
    SWIG_Callback3_t swig_callbackEstimate_s_domain;
    SWIG_Callback4_t swig_callbackEstimate_boundingbox;
    SWIG_Callback5_t swig_callbackUpdate;
    SWIG_Callback6_t swig_callbackArchiveOut;
    SWIG_Callback7_t swig_callbackArchiveIn;
    void swig_init_callbacks();
};

class SwigDirector_ChFunctionPosition_setpoint : public chrono::ChFunctionPosition_setpoint, public Swig::Director {

public:
    SwigDirector_ChFunctionPosition_setpoint();
    SwigDirector_ChFunctionPosition_setpoint(chrono::ChFunctionPosition_setpoint const &other);
    virtual ~SwigDirector_ChFunctionPosition_setpoint();
    virtual chrono::ChFunctionPosition_setpoint *Clone() const;
    virtual chrono::ChVector< > Get_p(double s) const;
    virtual chrono::ChVector< > Get_p_ds(double s) const;
    virtual chrono::ChVector< > Get_p_dsds(double s) const;
    virtual void Estimate_s_domain(double &smin, double &smax) const;
    virtual void Estimate_boundingbox(chrono::ChVector< > &pmin, chrono::ChVector< > &pmax) const;
    virtual void Update(double const t);
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual void SetSetpoint(chrono::ChVector< > p_setpoint, double s);
    virtual void SetSetpointAndDerivatives(chrono::ChVector< > p_setpoint, chrono::ChVector< > p_setpoint_ds, chrono::ChVector< > p_setpoint_dsds);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(double);
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(double);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackGet_p, SWIG_Callback1_t callbackGet_p_ds, SWIG_Callback2_t callbackGet_p_dsds, SWIG_Callback3_t callbackEstimate_s_domain, SWIG_Callback4_t callbackEstimate_boundingbox, SWIG_Callback5_t callbackUpdate, SWIG_Callback6_t callbackArchiveOut, SWIG_Callback7_t callbackArchiveIn, SWIG_Callback8_t callbackSetSetpoint, SWIG_Callback9_t callbackSetSetpointAndDerivatives);

private:
    SWIG_Callback0_t swig_callbackGet_p;
    SWIG_Callback1_t swig_callbackGet_p_ds;
    SWIG_Callback2_t swig_callbackGet_p_dsds;
    SWIG_Callback3_t swig_callbackEstimate_s_domain;
    SWIG_Callback4_t swig_callbackEstimate_boundingbox;
    SWIG_Callback5_t swig_callbackUpdate;
    SWIG_Callback6_t swig_callbackArchiveOut;
    SWIG_Callback7_t swig_callbackArchiveIn;
    SWIG_Callback8_t swig_callbackSetSetpoint;
    SWIG_Callback9_t swig_callbackSetSetpointAndDerivatives;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadable : public chrono::ChLoadable, public Swig::Director {

public:
    SwigDirector_ChLoadable();
    virtual ~SwigDirector_ChLoadable();
    virtual int LoadableGet_ndof_x();
    virtual int LoadableGet_ndof_w();
    virtual void LoadableGetStateBlock_x(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlock_w(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual int Get_field_ncoords();
    virtual int GetSubBlocks();
    virtual unsigned int GetSubBlockOffset(int nblock);
    virtual unsigned int GetSubBlockSize(int nblock);
    virtual bool IsSubBlockActive(int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackLoadableGet_ndof_x, SWIG_Callback1_t callbackLoadableGet_ndof_w, SWIG_Callback2_t callbackLoadableGetStateBlock_x, SWIG_Callback3_t callbackLoadableGetStateBlock_w, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGet_field_ncoords, SWIG_Callback6_t callbackGetSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables);

private:
    SWIG_Callback0_t swig_callbackLoadableGet_ndof_x;
    SWIG_Callback1_t swig_callbackLoadableGet_ndof_w;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlock_x;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlock_w;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGet_field_ncoords;
    SWIG_Callback6_t swig_callbackGetSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadableUVW : public chrono::ChLoadableUVW, public Swig::Director {

public:
    SwigDirector_ChLoadableUVW();
    virtual ~SwigDirector_ChLoadableUVW();
    virtual int LoadableGet_ndof_x();
    virtual int LoadableGet_ndof_w();
    virtual void LoadableGetStateBlock_x(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlock_w(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual int Get_field_ncoords();
    virtual int GetSubBlocks();
    virtual unsigned int GetSubBlockOffset(int nblock);
    virtual unsigned int GetSubBlockSize(int nblock);
    virtual bool IsSubBlockActive(int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);
    virtual void ComputeNF(double const U, double const V, double const W, chrono::ChVectorDynamic< > &Qi, double &detJ, chrono::ChVectorDynamic< > const &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual double GetDensity();
    virtual bool IsTetrahedronIntegrationNeeded();
    virtual bool IsTrianglePrismIntegrationNeeded();

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double, double, double, void *, void *, void *, void *, void *);
    typedef double (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback13_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback14_t)();
    void swig_connect_director(SWIG_Callback0_t callbackLoadableGet_ndof_x, SWIG_Callback1_t callbackLoadableGet_ndof_w, SWIG_Callback2_t callbackLoadableGetStateBlock_x, SWIG_Callback3_t callbackLoadableGetStateBlock_w, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGet_field_ncoords, SWIG_Callback6_t callbackGetSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables, SWIG_Callback11_t callbackComputeNF, SWIG_Callback12_t callbackGetDensity, SWIG_Callback13_t callbackIsTetrahedronIntegrationNeeded, SWIG_Callback14_t callbackIsTrianglePrismIntegrationNeeded);

private:
    SWIG_Callback0_t swig_callbackLoadableGet_ndof_x;
    SWIG_Callback1_t swig_callbackLoadableGet_ndof_w;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlock_x;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlock_w;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGet_field_ncoords;
    SWIG_Callback6_t swig_callbackGetSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    SWIG_Callback11_t swig_callbackComputeNF;
    SWIG_Callback12_t swig_callbackGetDensity;
    SWIG_Callback13_t swig_callbackIsTetrahedronIntegrationNeeded;
    SWIG_Callback14_t swig_callbackIsTrianglePrismIntegrationNeeded;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadableUV : public chrono::ChLoadableUV, public Swig::Director {

public:
    SwigDirector_ChLoadableUV();
    virtual ~SwigDirector_ChLoadableUV();
    virtual int LoadableGet_ndof_x();
    virtual int LoadableGet_ndof_w();
    virtual void LoadableGetStateBlock_x(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlock_w(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual int Get_field_ncoords();
    virtual int GetSubBlocks();
    virtual unsigned int GetSubBlockOffset(int nblock);
    virtual unsigned int GetSubBlockSize(int nblock);
    virtual bool IsSubBlockActive(int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);
    virtual void ComputeNF(double const U, double const V, chrono::ChVectorDynamic< > &Qi, double &detJ, chrono::ChVectorDynamic< > const &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);
    virtual chrono::ChVector< > ComputeNormal(double const U, double const V);
    virtual bool IsTriangleIntegrationNeeded();

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double, double, void *, void *, void *, void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback12_t)(double, double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback13_t)();
    void swig_connect_director(SWIG_Callback0_t callbackLoadableGet_ndof_x, SWIG_Callback1_t callbackLoadableGet_ndof_w, SWIG_Callback2_t callbackLoadableGetStateBlock_x, SWIG_Callback3_t callbackLoadableGetStateBlock_w, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGet_field_ncoords, SWIG_Callback6_t callbackGetSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables, SWIG_Callback11_t callbackComputeNF, SWIG_Callback12_t callbackComputeNormal, SWIG_Callback13_t callbackIsTriangleIntegrationNeeded);

private:
    SWIG_Callback0_t swig_callbackLoadableGet_ndof_x;
    SWIG_Callback1_t swig_callbackLoadableGet_ndof_w;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlock_x;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlock_w;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGet_field_ncoords;
    SWIG_Callback6_t swig_callbackGetSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    SWIG_Callback11_t swig_callbackComputeNF;
    SWIG_Callback12_t swig_callbackComputeNormal;
    SWIG_Callback13_t swig_callbackIsTriangleIntegrationNeeded;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadableU : public chrono::ChLoadableU, public Swig::Director {

public:
    SwigDirector_ChLoadableU();
    virtual ~SwigDirector_ChLoadableU();
    virtual int LoadableGet_ndof_x();
    virtual int LoadableGet_ndof_w();
    virtual void LoadableGetStateBlock_x(int block_offset, chrono::ChState &mD);
    virtual void LoadableGetStateBlock_w(int block_offset, chrono::ChStateDelta &mD);
    virtual void LoadableStateIncrement(unsigned int const off_x, chrono::ChState &x_new, chrono::ChState const &x, unsigned int const off_v, chrono::ChStateDelta const &Dv);
    virtual int Get_field_ncoords();
    virtual int GetSubBlocks();
    virtual unsigned int GetSubBlockOffset(int nblock);
    virtual unsigned int GetSubBlockSize(int nblock);
    virtual bool IsSubBlockActive(int nblock) const;
    virtual void LoadableGetVariables(std::vector< ChVariables * > &mvars);
    virtual void ComputeNF(double const U, chrono::ChVectorDynamic< > &Qi, double &detJ, chrono::ChVectorDynamic< > const &F, chrono::ChVectorDynamic< > *state_x, chrono::ChVectorDynamic< > *state_w);

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(unsigned int, void *, void *, unsigned int, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback7_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback8_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback9_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(double, void *, void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackLoadableGet_ndof_x, SWIG_Callback1_t callbackLoadableGet_ndof_w, SWIG_Callback2_t callbackLoadableGetStateBlock_x, SWIG_Callback3_t callbackLoadableGetStateBlock_w, SWIG_Callback4_t callbackLoadableStateIncrement, SWIG_Callback5_t callbackGet_field_ncoords, SWIG_Callback6_t callbackGetSubBlocks, SWIG_Callback7_t callbackGetSubBlockOffset, SWIG_Callback8_t callbackGetSubBlockSize, SWIG_Callback9_t callbackIsSubBlockActive, SWIG_Callback10_t callbackLoadableGetVariables, SWIG_Callback11_t callbackComputeNF);

private:
    SWIG_Callback0_t swig_callbackLoadableGet_ndof_x;
    SWIG_Callback1_t swig_callbackLoadableGet_ndof_w;
    SWIG_Callback2_t swig_callbackLoadableGetStateBlock_x;
    SWIG_Callback3_t swig_callbackLoadableGetStateBlock_w;
    SWIG_Callback4_t swig_callbackLoadableStateIncrement;
    SWIG_Callback5_t swig_callbackGet_field_ncoords;
    SWIG_Callback6_t swig_callbackGetSubBlocks;
    SWIG_Callback7_t swig_callbackGetSubBlockOffset;
    SWIG_Callback8_t swig_callbackGetSubBlockSize;
    SWIG_Callback9_t swig_callbackIsSubBlockActive;
    SWIG_Callback10_t swig_callbackLoadableGetVariables;
    SWIG_Callback11_t swig_callbackComputeNF;
    void swig_init_callbacks();
};

class SwigDirector_TSDAForceFunctor : public TSDAForceFunctor, public Swig::Director {

public:
    SwigDirector_TSDAForceFunctor();
    virtual ~SwigDirector_TSDAForceFunctor();
    virtual double evaluate(double time, double rest_length, double length, double vel, chrono::ChLinkTSDA const &link);

    typedef double (SWIGSTDCALL* SWIG_Callback0_t)(double, double, double, double, void *);
    void swig_connect_director(SWIG_Callback0_t callbackevaluate);

private:
    SWIG_Callback0_t swig_callbackevaluate;
    void swig_init_callbacks();
};

class SwigDirector_RSDATorqueFunctor : public RSDATorqueFunctor, public Swig::Director {

public:
    SwigDirector_RSDATorqueFunctor();
    virtual ~SwigDirector_RSDATorqueFunctor();
    virtual double evaluate(double time, double rest_angle, double angle, double vel, chrono::ChLinkRSDA const &link);

    typedef double (SWIGSTDCALL* SWIG_Callback0_t)(double, double, double, double, void *);
    void swig_connect_director(SWIG_Callback0_t callbackevaluate);

private:
    SWIG_Callback0_t swig_callbackevaluate;
    void swig_init_callbacks();
};

class SwigDirector_AddContactCallback : public chrono::ChContactContainer::AddContactCallback, public Swig::Director {

public:
    SwigDirector_AddContactCallback();
    virtual ~SwigDirector_AddContactCallback();
    virtual void OnAddContact(chrono::collision::ChCollisionInfo const &contactinfo, chrono::ChMaterialComposite *const material);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnAddContact);

private:
    SWIG_Callback0_t swig_callbackOnAddContact;
    void swig_init_callbacks();
};

class SwigDirector_ReportContactCallback : public chrono::ChContactContainer::ReportContactCallback, public Swig::Director {

public:
    SwigDirector_ReportContactCallback();
    virtual ~SwigDirector_ReportContactCallback();
    virtual bool OnReportContact(chrono::ChVector< > const &pA, chrono::ChVector< > const &pB, chrono::ChMatrix33< > const &plane_coord, double const &distance, double const &eff_radius, chrono::ChVector< > const &react_forces, chrono::ChVector< > const &react_torques, chrono::ChContactable *contactobjA, chrono::ChContactable *contactobjB);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *, double, double, void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnReportContact);

private:
    SWIG_Callback0_t swig_callbackOnReportContact;
    void swig_init_callbacks();
};

class SwigDirector_CustomCollisionCallback : public chrono::ChSystem::CustomCollisionCallback, public Swig::Director {

public:
    SwigDirector_CustomCollisionCallback();
    virtual ~SwigDirector_CustomCollisionCallback();
    virtual void OnCustomCollision(chrono::ChSystem *msys);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnCustomCollision);

private:
    SWIG_Callback0_t swig_callbackOnCustomCollision;
    void swig_init_callbacks();
};

class SwigDirector_ChReportProximityCallbackP : public ChReportProximityCallbackP, public Swig::Director {

public:
    SwigDirector_ChReportProximityCallbackP();
    virtual ~SwigDirector_ChReportProximityCallbackP();
    virtual bool OnReportProximity(chrono::collision::ChCollisionModel *modA, chrono::collision::ChCollisionModel *modB);

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnReportProximity);

private:
    SWIG_Callback0_t swig_callbackOnReportProximity;
    void swig_init_callbacks();
};

class SwigDirector_ChAddProximityCallbackP : public ChAddProximityCallbackP, public Swig::Director {

public:
    SwigDirector_ChAddProximityCallbackP();
    virtual ~SwigDirector_ChAddProximityCallbackP();
    virtual void OnAddProximity(chrono::collision::ChCollisionModel const &modA, chrono::collision::ChCollisionModel const &modB);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnAddProximity);

private:
    SWIG_Callback0_t swig_callbackOnAddProximity;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadBase : public chrono::ChLoadBase, public Swig::Director {

public:
    SwigDirector_ChLoadBase();
    virtual ~SwigDirector_ChLoadBase();
    virtual chrono::ChObj *Clone() const;
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual std::string &ArchiveContainerName();
    virtual int LoadGet_ndof_x();
    virtual int LoadGet_ndof_w();
    virtual void LoadGetStateBlock_x(chrono::ChState &mD);
    virtual void LoadGetStateBlock_w(chrono::ChStateDelta &mD);
    virtual void LoadStateIncrement(chrono::ChState const &x, chrono::ChStateDelta const &dw, chrono::ChState &x_new);
    virtual int LoadGet_field_ncoords();
    virtual void ComputeQ(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void ComputeJacobian(chrono::ChState *state_x, chrono::ChStateDelta *state_w, chrono::ChMatrixRef mK, chrono::ChMatrixRef mR, chrono::ChMatrixRef mM);
    virtual void CreateJacobianMatrices();
    virtual void Update(double time);
    virtual bool IsStiff();
    virtual void LoadIntLoadResidual_F(chrono::ChVectorDynamic< > &R, double c);
    virtual void LoadIntLoadResidual_Mv(chrono::ChVectorDynamic< > &R, chrono::ChVectorDynamic< > const &w, double c);
    virtual void InjectKRMmatrices(ChSystemDescriptor &mdescriptor);
    virtual void KRMmatricesLoad(double Kfactor, double Rfactor, double Mfactor);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback11_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(double, double, double);
    void swig_connect_director(SWIG_Callback0_t callbackArchiveOut, SWIG_Callback1_t callbackArchiveIn, SWIG_Callback2_t callbackLoadGet_ndof_x, SWIG_Callback3_t callbackLoadGet_ndof_w, SWIG_Callback4_t callbackLoadGetStateBlock_x, SWIG_Callback5_t callbackLoadGetStateBlock_w, SWIG_Callback6_t callbackLoadStateIncrement, SWIG_Callback7_t callbackLoadGet_field_ncoords, SWIG_Callback8_t callbackComputeQ, SWIG_Callback9_t callbackCreateJacobianMatrices, SWIG_Callback10_t callbackUpdate, SWIG_Callback11_t callbackIsStiff, SWIG_Callback12_t callbackLoadIntLoadResidual_F, SWIG_Callback13_t callbackLoadIntLoadResidual_Mv, SWIG_Callback14_t callbackInjectKRMmatrices, SWIG_Callback15_t callbackKRMmatricesLoad);

private:
    SWIG_Callback0_t swig_callbackArchiveOut;
    SWIG_Callback1_t swig_callbackArchiveIn;
    SWIG_Callback2_t swig_callbackLoadGet_ndof_x;
    SWIG_Callback3_t swig_callbackLoadGet_ndof_w;
    SWIG_Callback4_t swig_callbackLoadGetStateBlock_x;
    SWIG_Callback5_t swig_callbackLoadGetStateBlock_w;
    SWIG_Callback6_t swig_callbackLoadStateIncrement;
    SWIG_Callback7_t swig_callbackLoadGet_field_ncoords;
    SWIG_Callback8_t swig_callbackComputeQ;
    SWIG_Callback9_t swig_callbackCreateJacobianMatrices;
    SWIG_Callback10_t swig_callbackUpdate;
    SWIG_Callback11_t swig_callbackIsStiff;
    SWIG_Callback12_t swig_callbackLoadIntLoadResidual_F;
    SWIG_Callback13_t swig_callbackLoadIntLoadResidual_Mv;
    SWIG_Callback14_t swig_callbackInjectKRMmatrices;
    SWIG_Callback15_t swig_callbackKRMmatricesLoad;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadCustom : public chrono::ChLoadCustom, public Swig::Director {

public:
    SwigDirector_ChLoadCustom(std::shared_ptr< chrono::ChLoadable > mloadable);
    virtual ~SwigDirector_ChLoadCustom();
    virtual chrono::ChObj *Clone() const;
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual std::string &ArchiveContainerName();
    virtual int LoadGet_ndof_x();
    virtual int LoadGet_ndof_w();
    virtual void LoadGetStateBlock_x(chrono::ChState &mD);
    virtual void LoadGetStateBlock_w(chrono::ChStateDelta &mD);
    virtual void LoadStateIncrement(chrono::ChState const &x, chrono::ChStateDelta const &dw, chrono::ChState &x_new);
    virtual int LoadGet_field_ncoords();
    virtual void ComputeQ(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void ComputeJacobian(chrono::ChState *state_x, chrono::ChStateDelta *state_w, chrono::ChMatrixRef mK, chrono::ChMatrixRef mR, chrono::ChMatrixRef mM);
    virtual void CreateJacobianMatrices();
    virtual void Update(double time);
    virtual bool IsStiff();
    virtual void LoadIntLoadResidual_F(chrono::ChVectorDynamic< > &R, double c);
    virtual void LoadIntLoadResidual_Mv(chrono::ChVectorDynamic< > &R, chrono::ChVectorDynamic< > const &w, double c);
    virtual void InjectKRMmatrices(ChSystemDescriptor &mdescriptor);
    virtual void KRMmatricesLoad(double Kfactor, double Rfactor, double Mfactor);
    virtual chrono::ChVectorDynamic< > &GetQ();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback11_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(double, double, double);
    typedef void * (SWIGSTDCALL* SWIG_Callback16_t)();
    void swig_connect_director(SWIG_Callback0_t callbackArchiveOut, SWIG_Callback1_t callbackArchiveIn, SWIG_Callback2_t callbackLoadGet_ndof_x, SWIG_Callback3_t callbackLoadGet_ndof_w, SWIG_Callback4_t callbackLoadGetStateBlock_x, SWIG_Callback5_t callbackLoadGetStateBlock_w, SWIG_Callback6_t callbackLoadStateIncrement, SWIG_Callback7_t callbackLoadGet_field_ncoords, SWIG_Callback8_t callbackComputeQ, SWIG_Callback9_t callbackCreateJacobianMatrices, SWIG_Callback10_t callbackUpdate, SWIG_Callback11_t callbackIsStiff, SWIG_Callback12_t callbackLoadIntLoadResidual_F, SWIG_Callback13_t callbackLoadIntLoadResidual_Mv, SWIG_Callback14_t callbackInjectKRMmatrices, SWIG_Callback15_t callbackKRMmatricesLoad, SWIG_Callback16_t callbackGetQ);

private:
    SWIG_Callback0_t swig_callbackArchiveOut;
    SWIG_Callback1_t swig_callbackArchiveIn;
    SWIG_Callback2_t swig_callbackLoadGet_ndof_x;
    SWIG_Callback3_t swig_callbackLoadGet_ndof_w;
    SWIG_Callback4_t swig_callbackLoadGetStateBlock_x;
    SWIG_Callback5_t swig_callbackLoadGetStateBlock_w;
    SWIG_Callback6_t swig_callbackLoadStateIncrement;
    SWIG_Callback7_t swig_callbackLoadGet_field_ncoords;
    SWIG_Callback8_t swig_callbackComputeQ;
    SWIG_Callback9_t swig_callbackCreateJacobianMatrices;
    SWIG_Callback10_t swig_callbackUpdate;
    SWIG_Callback11_t swig_callbackIsStiff;
    SWIG_Callback12_t swig_callbackLoadIntLoadResidual_F;
    SWIG_Callback13_t swig_callbackLoadIntLoadResidual_Mv;
    SWIG_Callback14_t swig_callbackInjectKRMmatrices;
    SWIG_Callback15_t swig_callbackKRMmatricesLoad;
    SWIG_Callback16_t swig_callbackGetQ;
    void swig_init_callbacks();
};

class SwigDirector_ChLoadCustomMultiple : public chrono::ChLoadCustomMultiple, public Swig::Director {

public:
    SwigDirector_ChLoadCustomMultiple(std::vector< std::shared_ptr< chrono::ChLoadable > > &mloadables);
    SwigDirector_ChLoadCustomMultiple(std::shared_ptr< chrono::ChLoadable > mloadableA, std::shared_ptr< chrono::ChLoadable > mloadableB);
    SwigDirector_ChLoadCustomMultiple(std::shared_ptr< chrono::ChLoadable > mloadableA, std::shared_ptr< chrono::ChLoadable > mloadableB, std::shared_ptr< chrono::ChLoadable > mloadableC);
    virtual ~SwigDirector_ChLoadCustomMultiple();
    virtual chrono::ChObj *Clone() const;
    virtual void ArchiveOut(chrono::ChArchiveOut &marchive);
    virtual void ArchiveIn(chrono::ChArchiveIn &marchive);
    virtual std::string &ArchiveContainerName();
    virtual int LoadGet_ndof_x();
    virtual int LoadGet_ndof_w();
    virtual void LoadGetStateBlock_x(chrono::ChState &mD);
    virtual void LoadGetStateBlock_w(chrono::ChStateDelta &mD);
    virtual void LoadStateIncrement(chrono::ChState const &x, chrono::ChStateDelta const &dw, chrono::ChState &x_new);
    virtual int LoadGet_field_ncoords();
    virtual void ComputeQ(chrono::ChState *state_x, chrono::ChStateDelta *state_w);
    virtual void ComputeJacobian(chrono::ChState *state_x, chrono::ChStateDelta *state_w, chrono::ChMatrixRef mK, chrono::ChMatrixRef mR, chrono::ChMatrixRef mM);
    virtual void CreateJacobianMatrices();
    virtual void Update(double time);
    virtual bool IsStiff();
    virtual void LoadIntLoadResidual_F(chrono::ChVectorDynamic< > &R, double c);
    virtual void LoadIntLoadResidual_Mv(chrono::ChVectorDynamic< > &R, chrono::ChVectorDynamic< > const &w, double c);
    virtual void InjectKRMmatrices(ChSystemDescriptor &mdescriptor);
    virtual void KRMmatricesLoad(double Kfactor, double Rfactor, double Mfactor);
    virtual chrono::ChVectorDynamic< > &GetQ();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(double);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback11_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, double);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(double, double, double);
    typedef void * (SWIGSTDCALL* SWIG_Callback16_t)();
    void swig_connect_director(SWIG_Callback0_t callbackArchiveOut, SWIG_Callback1_t callbackArchiveIn, SWIG_Callback2_t callbackLoadGet_ndof_x, SWIG_Callback3_t callbackLoadGet_ndof_w, SWIG_Callback4_t callbackLoadGetStateBlock_x, SWIG_Callback5_t callbackLoadGetStateBlock_w, SWIG_Callback6_t callbackLoadStateIncrement, SWIG_Callback7_t callbackLoadGet_field_ncoords, SWIG_Callback8_t callbackComputeQ, SWIG_Callback9_t callbackCreateJacobianMatrices, SWIG_Callback10_t callbackUpdate, SWIG_Callback11_t callbackIsStiff, SWIG_Callback12_t callbackLoadIntLoadResidual_F, SWIG_Callback13_t callbackLoadIntLoadResidual_Mv, SWIG_Callback14_t callbackInjectKRMmatrices, SWIG_Callback15_t callbackKRMmatricesLoad, SWIG_Callback16_t callbackGetQ);

private:
    SWIG_Callback0_t swig_callbackArchiveOut;
    SWIG_Callback1_t swig_callbackArchiveIn;
    SWIG_Callback2_t swig_callbackLoadGet_ndof_x;
    SWIG_Callback3_t swig_callbackLoadGet_ndof_w;
    SWIG_Callback4_t swig_callbackLoadGetStateBlock_x;
    SWIG_Callback5_t swig_callbackLoadGetStateBlock_w;
    SWIG_Callback6_t swig_callbackLoadStateIncrement;
    SWIG_Callback7_t swig_callbackLoadGet_field_ncoords;
    SWIG_Callback8_t swig_callbackComputeQ;
    SWIG_Callback9_t swig_callbackCreateJacobianMatrices;
    SWIG_Callback10_t swig_callbackUpdate;
    SWIG_Callback11_t swig_callbackIsStiff;
    SWIG_Callback12_t swig_callbackLoadIntLoadResidual_F;
    SWIG_Callback13_t swig_callbackLoadIntLoadResidual_Mv;
    SWIG_Callback14_t swig_callbackInjectKRMmatrices;
    SWIG_Callback15_t swig_callbackKRMmatricesLoad;
    SWIG_Callback16_t swig_callbackGetQ;
    void swig_init_callbacks();
};

class SwigDirector_ChRandomShapeCreator_AddBodyCallback : public chrono::particlefactory::ChRandomShapeCreator::AddBodyCallback, public Swig::Director {

public:
    SwigDirector_ChRandomShapeCreator_AddBodyCallback();
    virtual ~SwigDirector_ChRandomShapeCreator_AddBodyCallback();
    virtual void OnAddBody(std::shared_ptr< chrono::ChBody > mbody, chrono::ChCoordsys< > mcoords, chrono::particlefactory::ChRandomShapeCreator &mcreator);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnAddBody);

private:
    SWIG_Callback0_t swig_callbackOnAddBody;
    void swig_init_callbacks();
};


#endif
