//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChTerrain : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal ChTerrain(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChTerrain obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChTerrain() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          vehiclePINVOKE.delete_ChTerrain(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ChTerrain() : this(vehiclePINVOKE.new_ChTerrain(), true) {
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void Synchronize(double time) {
    vehiclePINVOKE.ChTerrain_Synchronize(swigCPtr, time);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void Advance(double step) {
    vehiclePINVOKE.ChTerrain_Advance(swigCPtr, step);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double GetHeight(ChVectorD loc) {
    double ret = vehiclePINVOKE.ChTerrain_GetHeight(swigCPtr, ChVectorD.getCPtr(loc));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual ChVectorD GetNormal(ChVectorD loc) {
    ChVectorD ret = new ChVectorD(vehiclePINVOKE.ChTerrain_GetNormal(swigCPtr, ChVectorD.getCPtr(loc)), true);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual float GetCoefficientFriction(ChVectorD loc) {
    float ret = vehiclePINVOKE.ChTerrain_GetCoefficientFriction(swigCPtr, ChVectorD.getCPtr(loc));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void GetProperties(ChVectorD loc, SWIGTYPE_p_double height, ChVectorD normal, SWIGTYPE_p_float friction) {
    vehiclePINVOKE.ChTerrain_GetProperties(swigCPtr, ChVectorD.getCPtr(loc), SWIGTYPE_p_double.getCPtr(height), ChVectorD.getCPtr(normal), SWIGTYPE_p_float.getCPtr(friction));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RegisterHeightFunctor(SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChTerrain__HeightFunctor_t functor) {
    vehiclePINVOKE.ChTerrain_RegisterHeightFunctor(swigCPtr, SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChTerrain__HeightFunctor_t.getCPtr(functor));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RegisterNormalFunctor(SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChTerrain__NormalFunctor_t functor) {
    vehiclePINVOKE.ChTerrain_RegisterNormalFunctor(swigCPtr, SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChTerrain__NormalFunctor_t.getCPtr(functor));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RegisterFrictionFunctor(SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChTerrain__FrictionFunctor_t functor) {
    vehiclePINVOKE.ChTerrain_RegisterFrictionFunctor(swigCPtr, SWIGTYPE_p_std__shared_ptrT_chrono__vehicle__ChTerrain__FrictionFunctor_t.getCPtr(functor));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

}
