//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class HeightColorCallback : ColorCallback {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal HeightColorCallback(global::System.IntPtr cPtr, bool cMemoryOwn) : base(corePINVOKE.HeightColorCallback_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HeightColorCallback obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          corePINVOKE.delete_HeightColorCallback(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public HeightColorCallback(double hmin, double hmax, ChVectorD up) : this(corePINVOKE.new_HeightColorCallback__SWIG_0(hmin, hmax, ChVectorD.getCPtr(up)), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public HeightColorCallback(double hmin, double hmax) : this(corePINVOKE.new_HeightColorCallback__SWIG_1(hmin, hmax), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public HeightColorCallback(ChColor base_color, double hmin, double hmax, ChVectorD up) : this(corePINVOKE.new_HeightColorCallback__SWIG_2(ChColor.getCPtr(base_color), hmin, hmax, ChVectorD.getCPtr(up)), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public HeightColorCallback(ChColor base_color, double hmin, double hmax) : this(corePINVOKE.new_HeightColorCallback__SWIG_3(ChColor.getCPtr(base_color), hmin, hmax), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public override ChColor get(uint n, ChParticleCloud cloud) {
    ChColor ret = new ChColor(corePINVOKE.HeightColorCallback_get(swigCPtr, n, ChParticleCloud.getCPtr(cloud)), true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
