//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class HMMWV_AutomaticTransmissionShafts : ChAutomaticTransmissionShafts {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal HMMWV_AutomaticTransmissionShafts(global::System.IntPtr cPtr, bool cMemoryOwn) : base(vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(HMMWV_AutomaticTransmissionShafts obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          vehiclePINVOKE.delete_HMMWV_AutomaticTransmissionShafts(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public HMMWV_AutomaticTransmissionShafts(string name) : this(vehiclePINVOKE.new_HMMWV_AutomaticTransmissionShafts(name), true) {
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetGearRatios(vector_double fwd, SWIGTYPE_p_double rev) {
    vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_SetGearRatios(swigCPtr, vector_double.getCPtr(fwd), SWIGTYPE_p_double.getCPtr(rev));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double GetTransmissionBlockInertia() {
    double ret = vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_GetTransmissionBlockInertia(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetIngearShaftInertia() {
    double ret = vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_GetIngearShaftInertia(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetMotorshaftInertia() {
    double ret = vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_GetMotorshaftInertia(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetDriveshaftInertia() {
    double ret = vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_GetDriveshaftInertia(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetUpshiftRPM() {
    double ret = vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_GetUpshiftRPM(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetDownshiftRPM() {
    double ret = vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_GetDownshiftRPM(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetTorqueConverterCapacityFactorMap(SWIGTYPE_p_std__shared_ptrT_ChFunction_Recorder_t map) {
    vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_SetTorqueConverterCapacityFactorMap(swigCPtr, SWIGTYPE_p_std__shared_ptrT_ChFunction_Recorder_t.getCPtr(map));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetTorqeConverterTorqueRatioMap(SWIGTYPE_p_std__shared_ptrT_ChFunction_Recorder_t map) {
    vehiclePINVOKE.HMMWV_AutomaticTransmissionShafts_SetTorqeConverterTorqueRatioMap(swigCPtr, SWIGTYPE_p_std__shared_ptrT_ChFunction_Recorder_t.getCPtr(map));
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

}
