//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TranslationalDamperSuspension : ChTranslationalDamperSuspension {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal TranslationalDamperSuspension(global::System.IntPtr cPtr, bool cMemoryOwn) : base(vehiclePINVOKE.TranslationalDamperSuspension_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TranslationalDamperSuspension obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          vehiclePINVOKE.delete_TranslationalDamperSuspension(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public TranslationalDamperSuspension(string filename, bool has_shock, bool lock_arm) : this(vehiclePINVOKE.new_TranslationalDamperSuspension__SWIG_0(filename, has_shock, lock_arm), true) {
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public TranslationalDamperSuspension(SWIGTYPE_p_rapidjson__Document d, bool has_shock, bool lock_arm) : this(vehiclePINVOKE.new_TranslationalDamperSuspension__SWIG_1(SWIGTYPE_p_rapidjson__Document.getCPtr(d), has_shock, lock_arm), true) {
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double GetArmMass() {
    double ret = vehiclePINVOKE.TranslationalDamperSuspension_GetArmMass(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual ChVectorD GetArmInertia() {
    ChVectorD ret = new ChVectorD(vehiclePINVOKE.TranslationalDamperSuspension_GetArmInertia(swigCPtr), false);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetArmVisRadius() {
    double ret = vehiclePINVOKE.TranslationalDamperSuspension_GetArmVisRadius(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double GetSpringRestAngle() {
    double ret = vehiclePINVOKE.TranslationalDamperSuspension_GetSpringRestAngle(swigCPtr);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual TorqueFunctor GetSpringTorqueFunctor() {
    global::System.IntPtr cPtr = vehiclePINVOKE.TranslationalDamperSuspension_GetSpringTorqueFunctor(swigCPtr);
    TorqueFunctor ret = (cPtr == global::System.IntPtr.Zero) ? null : new TorqueFunctor(cPtr, true);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual TorqueFunctor GetDamperTorqueFunctor() {
    global::System.IntPtr cPtr = vehiclePINVOKE.TranslationalDamperSuspension_GetDamperTorqueFunctor(swigCPtr);
    TorqueFunctor ret = (cPtr == global::System.IntPtr.Zero) ? null : new TorqueFunctor(cPtr, true);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual ForceFunctor GetShockForceFunctor() {
    global::System.IntPtr cPtr = vehiclePINVOKE.TranslationalDamperSuspension_GetShockForceFunctor(swigCPtr);
    ForceFunctor ret = (cPtr == global::System.IntPtr.Zero) ? null : new ForceFunctor(cPtr, true);
    if (vehiclePINVOKE.SWIGPendingException.Pending) throw vehiclePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
